package org.omg.IOP;


/**
* org/omg/IOP/TAG_CODE_SETS.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /Users/java_re/workspace/8-2-build-macosx-x86_64/jdk8u144/9417/corba/src/share/classes/org/omg/PortableInterceptor/IOP.idl
* Friday, July 21, 2017 10:09:18 PM PDT
*/

public interface TAG_CODE_SETS
{

  /**
       * The code set component of the IOR multi-component profile structure
       * contains:
       * <ul>
       *   <li>server's native char code set and conversion code sets, and</li>
       *   <li>server's native wchar code set and conversion code sets.</li>
       * </ul>
       * Both char and wchar conversion code sets are listed in order of 
       * preference.
       */
  public static final int value = (int)(1L);
}
